services:
  postgres:
    networks:
      - tcc_network
    image: postgres:15
    container_name: tcc_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tcc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tcc_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    networks:
      - tcc_network
    image: minio/minio:latest
    container_name: tcc_minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spark-master:
    networks:
      - tcc_network
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile
    container_name: spark_master
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ..:/opt/spark/work-dir
      - spark_jars:/opt/spark/jars  # ← compartilha JARs
    environment:
      - PYTHONPATH=/opt/spark/work-dir/src
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    networks:
      - tcc_network
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile
    container_name: spark_worker
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - ..:/opt/spark/work-dir
      - spark_jars:/opt/spark/jars  # ← compartilha JARs
    environment:
      - PYTHONPATH=/opt/spark/work-dir/src
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master

  airflow-init:
    networks:
      - tcc_network
    build: ./airflow
    env_file:
      - .env
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
      spark-master:
        condition: service_started  # ← garante que o volume já foi populado
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/tcc_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow:/opt/spark/work-dir/src
    volumes:
      - ..:/opt/spark/work-dir
      - ../airflow/dags:/opt/airflow/dags
      - spark_jars:/opt/spark/jars  # ← mesmo volume
    command: >
      bash -c "
      airflow db migrate &&
      airflow connections create-default-connections &&
      airflow connections add spark_default \
        --conn-type spark \
        --conn-host spark-master \
        --conn-port 7077 || true &&
      airflow users create \
        --username admin \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email admin@example.com \
        --password admin || true
      "

  airflow:
    networks:
      - tcc_network
    build: ./airflow
    env_file:
      - .env
    container_name: airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/tcc_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow:/opt/spark/work-dir/src
    ports:
      - "8081:8080"
    volumes:
      - ..:/opt/spark/work-dir
      - ../airflow/dags:/opt/airflow/dags
      - spark_jars:/opt/spark/jars  # ← mesmo volume
    command: >
      bash -c "
      airflow webserver &
      airflow scheduler
      "

  streamlit:
    networks:
      - tcc_network
    build:
      context: ..
      dockerfile: docker/streamlit/Dockerfile
    container_name: tcc_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres

networks:
  tcc_network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  spark_jars: