services:
  postgres:
    image: postgres:15
    container_name: tcc_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tcc_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tcc_db"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    container_name: tcc_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spark-master:
    build:
      context: ./spark
    container_name: spark_master
    volumes:
      - ./spark/conf/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
      - /home/lucas/Projects/TCC-DATA-ENGINEERING:/opt/spark/work-dir
    environment:
      - PYTHONPATH=/opt/spark/work-dir/src
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "8080:8080"

  spark-worker:
    build:
      context: ./spark
    container_name: spark_worker
    volumes:
      - /home/lucas/Projects/TCC-DATA-ENGINEERING:/opt/spark/work-dir
    environment:
      - PYTHONPATH=/opt/spark/work-dir/src
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    depends_on:
      - spark-master

  airflow-init:
    image: apache/airflow:2.8.1
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/tcc_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: AwPSxv-IQc1rZ-lBU6UEZW3mUqlRsGv_NBFIkvI4JOk=
    command: >
      bash -c "
      airflow db migrate &&
      airflow connections create-default-connections &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true
      "

  airflow:
    image: apache/airflow:2.8.1
    container_name: airflow
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin@postgres/tcc_db
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__FERNET_KEY: AwPSxv-IQc1rZ-lBU6UEZW3mUqlRsGv_NBFIkvI4JOk=
    ports:
      - "8081:8080"
    command: >
      bash -c "
      airflow webserver &
      airflow scheduler
      "

  streamlit:
    build:
      context: ..
      dockerfile: docker/streamlit/Dockerfile
    container_name: tcc_streamlit
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  postgres_data:
  minio_data: